import React, { useState } from 'react';
import { EventBudgetItem, BudgetItemCategory, RaceEvent } from '../types';
import { useTranslations } from '../hooks/useTranslations';
import { formatFinancialDate } from '../utils/financialUtils';
import { enrichBudgetWithAccounting } from '../utils/accountingEntryUtils';
import { generateId } from '../utils/themeUtils';

interface BudgetFormProps {
  item?: EventBudgetItem | null;
  raceEvents?: RaceEvent[];
  onSave: (item: EventBudgetItem) => void;
  onCancel: () => void;
}

const LOCALE_MAP: Record<string, string> = { fr: 'fr-FR', en: 'en-GB' };

const BudgetForm: React.FC<BudgetFormProps> = ({ item, raceEvents, onSave, onCancel }) => {
  const { t, language } = useTranslations();
  const locale = LOCALE_MAP[language] || 'fr-FR';

  const [formData, setFormData] = useState<Omit<EventBudgetItem, 'id'>>({
    eventId: item?.eventId || '',
    category: item?.category || BudgetItemCategory.FRAIS_DIVERS,
    description: item?.description || '',
    estimatedCost: item?.estimatedCost || 0,
    actualCost: item?.actualCost || undefined,
    notes: item?.notes || '',
    isAutoGenerated: item?.isAutoGenerated || false,
    sourceVehicleId: item?.sourceVehicleId || undefined,
    sourceStaffId: item?.sourceStaffId || undefined,
    proofDocumentId: item?.proofDocumentId || undefined,
    receiptDate: item?.receiptDate || new Date().toISOString().slice(0, 10),
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const selectedEvent = raceEvents?.find((ev) => ev.id === formData.eventId);
    const receiptDate =
      formData.receiptDate ||
      selectedEvent?.date?.slice(0, 10) ||
      new Date().toISOString().slice(0, 10);
    const budgetItem: EventBudgetItem = enrichBudgetWithAccounting(
      {
        id: item?.id || generateId(),
        eventId: formData.eventId || undefined,
        category: formData.category,
        description: formData.description,
        estimatedCost: formData.estimatedCost,
        actualCost: formData.actualCost,
        notes: formData.notes,
        isAutoGenerated: formData.isAutoGenerated,
        sourceVehicleId: formData.sourceVehicleId,
        sourceStaffId: formData.sourceStaffId,
        proofDocumentId: formData.proofDocumentId,
        receiptDate,
        accountingCode: item?.accountingCode,
        accountingLabel: item?.accountingLabel,
      },
      language
    );
    onSave(budgetItem);
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <div>
        <label htmlFor="budget-event" className="block text-sm font-medium text-gray-700">
          {t('formEvent')}
        </label>
        <select
          id="budget-event"
          value={formData.eventId || ''}
          onChange={(e) => {
            const eventId = e.target.value;
            const selectedEvent = raceEvents?.find((ev) => ev.id === eventId);
            setFormData((prev) => ({
              ...prev,
              eventId,
              receiptDate:
                prev.receiptDate ||
                selectedEvent?.date?.slice(0, 10) ||
                prev.receiptDate,
            }));
          }}
          className="mt-1 block w-full border border-gray-300 rounded-md px-3 py-2 focus:outline-none focus:ring-blue-500 focus:border-blue-500"
        >
          <option value="">{t('formEventGeneral')}</option>
          {raceEvents?.map((event) => (
            <option key={event.id} value={event.id}>
              {event.name} - {formatFinancialDate(event.date, locale)}
            </option>
          ))}
        </select>
      </div>

      <div>
        <label htmlFor="budget-receipt-date" className="block text-sm font-medium text-gray-700">
          {t('formDate')}
        </label>
        <input
          id="budget-receipt-date"
          type="date"
          value={formData.receiptDate || ''}
          onChange={(e) => setFormData((prev) => ({ ...prev, receiptDate: e.target.value }))}
          className="mt-1 block w-full border border-gray-300 rounded-md px-3 py-2 focus:outline-none focus:ring-blue-500 focus:border-blue-500"
        />
      </div>

      <div>
        <label htmlFor="budget-category" className="block text-sm font-medium text-gray-700">
          {t('formCategory')}
        </label>
        <select
          id="budget-category"
          value={formData.category}
          onChange={(e) => setFormData((prev) => ({ ...prev, category: e.target.value as BudgetItemCategory }))}
          className="mt-1 block w-full border border-gray-300 rounded-md px-3 py-2 focus:outline-none focus:ring-blue-500 focus:border-blue-500"
          required
        >
          {Object.values(BudgetItemCategory).map((category) => (
            <option key={category} value={category}>
              {category}
            </option>
          ))}
        </select>
      </div>

      <div>
        <label htmlFor="budget-description" className="block text-sm font-medium text-gray-700">
          {t('formDescription')}
        </label>
        <input
          id="budget-description"
          type="text"
          value={formData.description}
          onChange={(e) => setFormData((prev) => ({ ...prev, description: e.target.value }))}
          className="mt-1 block w-full border border-gray-300 rounded-md px-3 py-2 focus:outline-none focus:ring-blue-500 focus:border-blue-500"
          required
        />
      </div>

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        <div>
          <label htmlFor="budget-estimated" className="block text-sm font-medium text-gray-700">
            {t('formEstimatedCost')}
          </label>
          <input
            id="budget-estimated"
            type="number"
            value={formData.estimatedCost}
            onChange={(e) => setFormData((prev) => ({ ...prev, estimatedCost: parseFloat(e.target.value) || 0 }))}
            className="mt-1 block w-full border border-gray-300 rounded-md px-3 py-2 focus:outline-none focus:ring-blue-500 focus:border-blue-500"
            min="0"
            step="0.01"
            required
          />
        </div>

        <div>
          <label htmlFor="budget-actual" className="block text-sm font-medium text-gray-700">
            {t('formActualCost')}
          </label>
          <input
            id="budget-actual"
            type="number"
            value={formData.actualCost ?? ''}
            onChange={(e) =>
              setFormData((prev) => ({
                ...prev,
                actualCost: e.target.value ? parseFloat(e.target.value) : undefined,
              }))
            }
            className="mt-1 block w-full border border-gray-300 rounded-md px-3 py-2 focus:outline-none focus:ring-blue-500 focus:border-blue-500"
            min="0"
            step="0.01"
          />
        </div>
      </div>

      <div>
        <label htmlFor="budget-notes" className="block text-sm font-medium text-gray-700">
          {t('formNotes')}
        </label>
        <textarea
          id="budget-notes"
          value={formData.notes}
          onChange={(e) => setFormData((prev) => ({ ...prev, notes: e.target.value }))}
          rows={3}
          className="mt-1 block w-full border border-gray-300 rounded-md px-3 py-2 focus:outline-none focus:ring-blue-500 focus:border-blue-500"
        />
      </div>

      <div className="flex justify-end space-x-3 pt-4">
        <button
          type="button"
          onClick={onCancel}
          className="px-4 py-2 border border-gray-300 rounded-md text-sm font-medium text-gray-700 hover:bg-gray-50"
        >
          {t('formCancel')}
        </button>
        <button
          type="submit"
          className="px-4 py-2 bg-blue-600 border border-transparent rounded-md text-sm font-medium text-white hover:bg-blue-700"
        >
          {item ? t('formEdit') : t('formAdd')}
        </button>
      </div>
    </form>
  );
};

export default BudgetForm;
