import { EventBudgetItem, IncomeItem, RaceEvent } from '../types';
import {
  buildEventNameMap,
  formatFinancialDate,
  getBudgetItemCost,
} from './financialUtils';
import { resolveIncomeAccountingCode } from '../constants/accountingCodes';

function escapeCsv(value: string | number | undefined): string {
  const str = value === undefined || value === null ? '' : String(value);
  if (str.includes(',') || str.includes('"') || str.includes('\n')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

export interface AccountingExportOptions {
  raceEvents?: RaceEvent[];
  locale?: string;
}

/** Export comptable CSV (budgets course + revenus). */
export function exportAccountingCsv(
  teamName: string,
  budgetItems: EventBudgetItem[],
  incomeItems: IncomeItem[],
  options: AccountingExportOptions = {}
): void {
  const { raceEvents, locale = 'fr-FR' } = options;
  const eventNames = buildEventNameMap(raceEvents);

  const lines: string[] = [
    'Type,Date,Libellé,Catégorie,Compte comptable,Libellé compte,Journal,Montant (EUR),Événement,Contact,Contrat début,Contrat fin,Notes',
  ];

  const sortedExpenses = [...budgetItems].sort((a, b) =>
    (a.description || '').localeCompare(b.description || '', locale)
  );

  for (const item of sortedExpenses) {
    const amount = getBudgetItemCost(item);
    const eventLabel = item.eventId
      ? eventNames.get(item.eventId) || item.eventId
      : 'Général';

    lines.push(
      [
        'Dépense',
        item.receiptDate || '',
        item.description || '',
        item.category || '',
        item.accountingCode || '',
        item.accountingLabel || '',
        'OD',
        amount,
        eventLabel,
        '',
        '',
        '',
        item.isAutoGenerated ? `[Auto] ${item.notes || ''}`.trim() : item.notes || '',
      ]
        .map(escapeCsv)
        .join(',')
    );
  }

  const sortedIncome = [...incomeItems].sort((a, b) =>
    (b.date || '').localeCompare(a.date || '')
  );

  for (const item of sortedIncome) {
    const accounting = resolveIncomeAccountingCode(item.category);
    lines.push(
      [
        'Revenu',
        item.date || '',
        item.description || '',
        item.category || '',
        item.accountingCode || accounting.code,
        item.accountingLabel || accounting.label,
        item.accountingJournal || accounting.journal,
        item.amount ?? 0,
        '',
        item.clientName || item.sponsorshipContactName || '',
        item.sponsorshipContractStart
          ? formatFinancialDate(item.sponsorshipContractStart, locale)
          : '',
        item.sponsorshipContractEnd
          ? formatFinancialDate(item.sponsorshipContractEnd, locale)
          : '',
        item.invoiceNumber
          ? `Facture ${item.invoiceNumber} (${item.invoiceStatus || ''})`
          : item.notes || '',
      ]
        .map(escapeCsv)
        .join(',')
    );
  }

  const blob = new Blob(['\uFEFF' + lines.join('\n')], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `LogiCycle_Compta_${teamName.replace(/\s+/g, '_')}_${new Date().toISOString().slice(0, 10)}.csv`;
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
